typography_spectrum: 0.8945242930203676
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3332392431329936
  lightness: 0.5037007660139352
  saturation: 0.6697450848296285
  rhythmicContrast: 0.5285798374097794
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7630608705803752
analytics:
  google: null
  facebook: null
  twitter: null
name: Ontario HBOT
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ontario HBOT
purpose: []
